// Dashboard markup shell.
//
// The single largest string in the frontend used to live inside render.js, which
// buried the orchestration logic. It is a declarative template, so it lives here.

import {terminalShell} from "./terminal.js";
import {operationsShell} from "./operations.js";
import {trainingShell} from "./views/training.js";

export function shell() {
  return `<div class="app">
<header class="global-header"><div class="brand"><span class="brand-mark">P</span><span>Paper Futures</span><em>模拟</em></div><nav class="global-nav"><button class="active" data-view="overview">总览</button><button data-view="trade">模拟交易</button><button data-view="markets">市场</button><button data-view="analytics">分析</button><button data-view="audit">审计</button><button data-view="models">模型</button><button data-view="training">训练</button><button data-view="system">健康</button></nav><div class="header-tools"><span class="live-dot" id="connDot"></span><span id="connText">连接中</span><button class="icon-btn" id="refreshBtn" title="刷新">↻</button></div></header>
<div class="workspace"><aside class="sidebar"><div class="account-label">模拟合约账户</div><div class="account-id">USDT-M · Cross</div><nav class="side-nav"><button class="active" data-view="overview">资产总览</button><button data-view="trade">持仓与订单</button><button data-view="trade" data-trade-tab="trades">成交记录</button><button data-view="analytics">绩效分析</button><button data-view="audit">会话审计</button><button data-view="models">模型中心</button><button data-view="system">系统健康</button></nav><div class="feed-state"><div><span class="live-dot" id="sideDot"></span><span id="freshText">等待行情</span></div><small>PUBLIC MARKET DATA</small></div></aside>
<main class="main"><div class="page-head"><div><h1 id="pageTitle">资产总览</h1><p id="pageSubtitle">模拟账户净值与合约风险</p></div><div class="head-meta"><span id="lastUpdate">--</span><span class="paper-pill">PAPER ONLY</span></div></div><div class="error" id="errorBox"></div>
<section id="overview" class="view active">
<div class="asset-hero"><div class="asset-main"><div class="eyebrow">预估总资产 <button class="eye-btn" id="privacyBtn" title="隐藏或显示资产">◉</button></div><div class="hero-value private" id="equity">--</div><div class="hero-sub"><span id="returnPct">--</span><span>累计收益</span></div></div><div class="asset-actions"><button class="primary" data-view="trade">管理模拟交易</button><button data-view="analytics">查看分析</button></div></div>
<div class="balance-grid"><div><span>钱包余额</span><strong class="private" id="cash">--</strong></div><div><span>可用保证金</span><strong class="private" id="availableMargin">--</strong></div><div><span>未实现盈亏</span><strong class="private" id="unrealizedPnl">--</strong></div><div><span>已实现盈亏（本会话）</span><strong class="private" id="realizedPnl">--</strong><small id="realizedPnlNote">--</small></div><div><span>保证金余额</span><strong class="private" id="marginBalance">--</strong></div></div>
<div class="overview-grid"><div class="panel chart-panel"><div class="panel-head"><div><h2>资产走势</h2><p>账户总权益</p></div><span id="metricSummary">--</span></div><canvas id="overviewChart" class="chart" width="1200" height="310"></canvas></div><div class="panel risk-panel"><div class="panel-head"><div><h2>风险概览</h2><p id="riskSubtitle">Cross 保证金</p></div><span class="status-badge" id="riskStatus">正常</span></div><dl class="stats-list risk-profile-stats"><div><dt>风险档位</dt><dd id="activeProfile">--</dd></div><div><dt>单笔风险</dt><dd id="profileRisk">--</dd></div><div><dt>组合风险</dt><dd id="profilePortfolioRisk">--</dd></div><div><dt>目标敞口</dt><dd id="profileExposure">--</dd></div><div><dt>持仓上限</dt><dd id="profilePositions">--</dd></div></dl><div class="risk-gauge"><div class="gauge-line"><span id="marginUsageBar"></span></div><div><strong id="marginUsage">--</strong><small>保证金使用率</small></div></div><dl class="stats-list"><div><dt>持仓名义价值</dt><dd id="totalNotional">--</dd></div><div><dt>已用保证金</dt><dd id="usedMargin">--</dd></div><div><dt>维持保证金</dt><dd id="maintenanceMargin">--</dd></div><div><dt>账户杠杆</dt><dd id="leverage">--</dd></div></dl></div></div>
<div class="panel"><div class="panel-head"><div><h2>当前持仓</h2><p id="positionSummary">0 个持仓</p></div><button class="text-btn" data-view="trade">查看全部 →</button></div><div class="table-wrap"><table><thead><tr><th>合约</th><th>方向 / 杠杆</th><th>持仓量</th><th>开仓价格</th><th>标记价格</th><th>未实现盈亏</th><th>收益率</th><th>保证金</th><th>强平价格</th><th>止盈 / 止损</th><th>操作</th></tr></thead><tbody id="overviewPositions"></tbody></table></div></div>
<div class="market-strip" id="marketStrip"></div></section>
<section id="trade" class="view">${terminalShell()}<div class="session-bar"><div><span class="session-state" id="sessionState">未启动</span><strong id="sessionTitle">模拟交易会话</strong><small id="sessionMeta">配置资金与策略范围后启动</small></div><div class="session-config"><label>初始资金<input id="initialCash" type="number" min="100" max="100000" step="100" value="10000" title="100 - 100000"></label><label>杠杆<select id="sessionLeverage"><option>1</option><option selected>3</option><option>5</option><option>10</option><option>20</option></select></label><label>选币<select id="sessionSource"><option value="trained">模型训练品种</option><option value="gainers">涨幅榜</option><option value="losers">跌幅榜</option></select></label><label>数量<input id="symbolCount" type="number" min="1" max="10" value="3"></label><label>风险档位<select id="riskProfileSelect"></select></label></div><div class="session-actions"><button class="primary" id="startSession">启动</button><button id="pauseSession">暂停</button><button id="resumeSession">继续</button><button class="danger" id="endSession">结束</button></div></div>
<div class="session-risk-bar"><span class="risk-profile-current">风险档位 <strong id="sessionProfileName">--</strong></span><span class="risk-profile-readout" id="sessionProfileReadout">--</span><label class="risk-profile-live">运行中切换<select id="liveProfileSelect"></select></label><button id="applyProfile">切换档位</button></div>
<div class="session-risk-bar"><span class="risk-profile-current">止盈止损 <strong id="sessionExitName">--</strong></span><span class="risk-profile-readout" id="sessionExitReadout">--</span><label class="risk-profile-live">运行中切换<select id="liveExitSelect"></select></label><button id="applyExit">切换策略</button></div>
<div class="trade-summary"><div><span>账户权益</span><strong class="private" id="tradeEquity">--</strong></div><div><span>今日/累计盈亏</span><strong class="private" id="tradePnl">--</strong></div><div><span>可用余额</span><strong class="private" id="tradeAvailable">--</strong></div><div><span>持仓名义价值</span><strong id="tradeNotional">--</strong></div><div><span>累计费用</span><strong id="tradeFees">--</strong></div><div><span>胜率</span><strong id="tradeWinRate">--</strong></div></div>
<div class="panel trade-ledger"><div class="tabs" id="tradeTabs"><button class="active" data-tab="positions">持仓 <b id="positionCount">0</b></button><button data-tab="open-orders">当前委托 <b id="openOrderCount">0</b></button><button data-tab="orders">历史委托</button><button data-tab="trades">成交记录 <b id="tradeCount">0</b></button></div><div class="ledger-tools"><input id="ledgerSearch" placeholder="搜索合约或订单号"><select id="ledgerSide"><option value="">全部方向</option><option value="LONG">多头 / 买入</option><option value="SHORT">空头 / 卖出</option></select><span id="ledgerSummary">--</span></div>
<div class="tab-pane active" data-pane="positions"><div class="table-wrap"><table><thead><tr><th>合约</th><th>方向 / 杠杆</th><th>持仓量</th><th>名义价值</th><th>开仓 / 标记</th><th>未实现盈亏</th><th>收益率</th><th>保证金</th><th>强平价</th><th>止盈 / 止损</th><th>开仓时间</th><th>操作</th></tr></thead><tbody id="positionRows"></tbody></table></div></div>
<div class="tab-pane" data-pane="open-orders"><div class="table-wrap"><table><thead><tr><th>时间</th><th>合约</th><th>方向</th><th>类型</th><th>委托价格</th><th>委托量 / 已成交</th><th>只减仓</th><th>状态</th><th>订单号</th><th>操作</th></tr></thead><tbody id="openOrderRows"></tbody></table></div></div>
<div class="tab-pane" data-pane="orders"><div class="table-wrap"><table><thead><tr><th>创建时间</th><th>更新时间</th><th>合约</th><th>方向</th><th>类型</th><th>价格</th><th>数量 / 成交</th><th>状态</th><th>订单号</th></tr></thead><tbody id="orderHistoryRows"></tbody></table></div></div>
<div class="tab-pane" data-pane="trades"><div class="table-wrap"><table><thead><tr><th>平仓时间</th><th>合约</th><th>方向</th><th>数量</th><th>开仓 / 平仓</th><th>净盈亏</th><th>收益率</th><th>手续费</th><th>资金费</th><th>持仓时长</th><th>原因</th><th></th></tr></thead><tbody id="tradeRows"></tbody></table></div></div></div></section>
<section id="markets" class="view"><div class="panel"><div class="panel-head"><div><h2>USDT 永续市场</h2><p>Binance 公共行情</p></div><div class="controls"><input id="marketSearch" placeholder="搜索合约"><select id="marketSort"><option value="change">涨跌幅</option><option value="volume">成交额</option><option value="symbol">合约名称</option></select></div></div><div class="table-wrap"><table><thead><tr><th>合约</th><th>最新价</th><th>24h 涨跌</th><th>成交额</th><th>资金费率</th><th>策略信号</th><th>更新</th></tr></thead><tbody id="marketRows"></tbody></table></div></div></section>
<section id="analytics" class="view"><div class="analytics-kpis"><div><span>总交易数</span><strong id="analyticsTrades">--</strong></div><div><span>胜率</span><strong id="analyticsWin">--</strong></div><div><span>最大回撤</span><strong id="analyticsDrawdown">--</strong></div><div><span>利润因子</span><strong id="analyticsProfitFactor">--</strong></div></div><div class="panel"><div class="panel-head"><div><h2>权益曲线</h2><p>历史账户权益</p></div></div><canvas id="analyticsChart" class="chart" width="1200" height="360"></canvas></div></section>
<section id="audit" class="view"><div class="panel"><div class="panel-head"><div><h2>模拟会话历史</h2><p>完整生命周期审计</p></div></div><div class="table-wrap"><table><thead><tr><th>会话 ID</th><th>状态</th><th>开始</th><th>结束</th><th>初始资金</th><th>杠杆</th><th>成交</th><th>净盈亏</th><th>结束原因</th></tr></thead><tbody id="historyRows"></tbody></table></div></div><div class="panel"><div class="panel-head"><div><h2>事件流</h2><p id="eventCount">0 条事件</p></div></div><div class="table-wrap audit-table"><table><thead><tr><th>时间</th><th>类型</th><th>载荷</th></tr></thead><tbody id="eventRows"></tbody></table></div></div></section>
${operationsShell()}
${trainingShell()}</main></div><div class="drawer-backdrop" id="drawerBackdrop"></div><aside class="trade-drawer" id="tradeDrawer"><button class="drawer-close" id="drawerClose">×</button><div id="drawerContent"></div></aside></div>`;
}
